# Github action workflow to deploy the infrastructure
# this workflow is deploy manually from the github actions tab
---
name: Infrastructure setup
on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Name of the stack to deploy'
        required: true
        default: 'n26'
      region:
        description: 'Region to deploy'
        required: true
        default: 'us-east-1'
      dr-region:
        description: 'Disaster Recovery Region'
        required: true
        default: 'us-east-2'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      
      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
      
      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/

      - name: Terraform plan
        run: |
          terraform plan \
            -var "name=${{ github.event.inputs.stack-name }}" \
            -var "region=${{ github.event.inputs.region }}" \
            -var "dr_region=${{ github.event.inputs.dr-region }}" \
            -out "planfile"
        working-directory: infrastructure/
      # - name: Terraform apply
      #   run: |
      #     terraform apply -auto-approve \
      #       -var "name=${{ github.event.inputs.stack-name }}" \
      #       -var "region=${{ github.event.inputs.region }}" \
      #       -var "dr_region=${{ github.event.inputs.dr-region }}" \

      #   working-directory: infrastructure/

